.TH junon 7
.VB
.DS
.nf
    __         _         __
 __|  |___ ___| |_    __|  |_ _ ___ ___ ___
|  |  | . |_ -|   |  |  |  | | |   | . |   |
|_____|___|___|_|_|  |_____|___|_|_|___|_|_|
.fi
.DE
.VE
.SH ABOUT
.HY
Hello, I am 0xfab1.

This is an example resume written for 0xfab1.net

.SH CONTACT
Please don't contact me at the following email address:

.RS
your name at 0xfab1 dot net
.RE
.SH LINKS
Links to relevant profiles or portfolios:
.NH
.RS
.TS
expand;
lb rb
l r.
SITE	URL
Github	https://github.com/FullByte
LinkedIn	https://www.linkedin.com/in/0xfab1-is-not-on-linkedin/
.TE
.RE
.SH PROFICIENCIES
.HY
.SM The following lists are in no particular order.

I am an expert in:
.NH
.RS
.TS
expand;
l l l l.
something	else	things that dont suck	python
markdown	but not	html	lol
you get the	idea
.TE
.RE

.HY
I am experienced with:
.NH
.RS
.TS
expand;
l l l l.
something	else	things that dont suck	python
markdown	but not	html	lol
you get the	idea
.TE
.RE

.HY
I am familiar with or have used:
.NH
.RS
.TS
expand;
l l l l.
something	else	things that dont suck	python
markdown	but not	html	lol
you get the	idea
.TE
.RE
.SH PROJECTS
.HY
I am a creator or current maintainer of the following notable projects:
.NH
.RS
.TS
expand;
lb cb rb
l c r.
NAME	LANGUAGE	URL
0xfab1.net	markdown	https://github.com/FullByte/FullByte.github.io/
.TE
.RE
.SH WORK EXPERIENCE
.HY
.TS
expand;
lb s
l r.
Software Engineer
Company GmbH (Berlin, Germany)	(Jan 2020 - Jan 2022)
.TE
.RS
.IP \[bu] 2
Did stuff which I dont regret.
.RE
.TS
expand;
lb s
l r.
Senior Software Engineer
Large Corp. (Munich, Germany)	(May 2015 - Dec 2019)
.TE
.RS
.IP \[bu] 2
Designed and implemented stuff.
.RE
.TS
expand;
lb s
l r.
Senior Fullstack Engineer
Tiny Ops (Nowhere, Germany)	(Oct 2009 - Apr 2015)
.TE
.RS
.IP \[bu] 2
Orchestrated stuff.
.IP \[bu] 2
Designed, implemented and managed everything.
.RE
.SH NOTABLE CONTRIBUTIONS
.HY
I have contributed to the following Github projects:
.NH
.RS
.TS
expand;
l l l l.
FullByte.github.io
.TE
.RE
.SH REFERENCES
References available upon request.
