site_name: "0xfab1"
site_url: https://0xfab1.net
repo_url: https://github.com/FullByte/FullByte.github.io
site_description: "0xfab1 wiki"
site_author: "0xfab1"

theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  language: en
  palette:
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  highlightjs: true
  favicon: assets/images/0xfab1.png
  logo: assets/images/0xfab1.png
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - header.autohide
    - announce.dismiss

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zerogdoubled
    - icon: fontawesome/brands/github
      link: https://github.com/FullByte
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/1132374314/playlists
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/0xfab1/0xfab1.net
    - icon: fontawesome/brands/itch-io
      link: https://0xfab1.itch.io/
    - icon: fontawesome/brands/fort-awesome
      link: https://www.instructables.com/member/FullByte/
    - icon: fontawesome/brands/leanpub
      link: https://www.librarycat.org/lib/0xfab1
    - icon: fontawesome/brands/laravel
      link: https://boardgamegeek.com/collection/user/zerogdoubled
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/0xfab1
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      clickable_checkbox: true
