# Wiki Infos
site_name: "0xfab1"
site_url: https://0xfab1.net
repo_url: https://github.com/FullByte/FullByte.github.io
site_description: "0xfab1 wiki"
site_author: "Fabian"

# Configuration
theme:
  name: material
  static_templates:
    - 404.html
  language: en
  palette:
    scheme: slate
    primary: green
    accent: yellow
  highlightjs: true
  favicon: icons/favicon.ico
  icon:
    logo: logo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

# Social
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zerogdoubled
    - icon: fontawesome/brands/github
      link: https://github.com/FullByte

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.details
