site_name: "0xfab1"
site_url: https://0xfab1.net
repo_url: https://github.com/FullByte/FullByte.github.io
site_description: >-
  This is the personal website of 0xfab1. It mainly contains blog entries on IT tech stuff, games, making things and art.
site_author: "0xfab1"
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
    - health.html
  language: en
  palette:
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  highlightjs: true
  favicon: assets/images/0xfab1.png
  logo: assets/images/0xfab1.png
  font: false
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.indexes
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - rss:
      match_path: "index.md|tech/index.md|make/index.md|about/index.md|tech/.*|make/.*"
      date_from_meta:
        as_creation: "date"
        as_update: "modified"
      categories:
        - tags
      abstract_chars_count: 160
      feed_ttl: 1440
      pretty_print: false
      length: 20
  # RSS plugin disabled - was causing extreme build times by processing all 449+ files
  # - rss:
  #     match_path: ".*"
  #     date_from_meta:
  #       as_creation: "date"
  #       as_update: "modified"
  #     categories:
  #       - tags
  #     abstract_chars_count: 160
  #     feed_ttl: 1440
  #     pretty_print: true
  
  # Git revision plugin disabled - was causing extreme build times on large repos  
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     enable_git_follow: false
  #     enable_parallel_processing: false
  #     type: timeago
  #     fallback_to_build_date: true
  #     exclude:
  #       - index.md
  #     strict: false
  # HTML proofer disabled for faster development builds
  # - htmlproofer:
  #     enabled: true
  #     validate_external_urls: false
  #     raise_error: false

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FullByte
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/0xfab1

# Include media files in the build
extra_css: []
extra_javascript: []

# Copy additional files to site
docs_dir: docs
site_dir: site

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences
