site_name: "0xfab1"
site_url: https://0xfab1.net
repo_url: https://github.com/FullByte/FullByte.github.io
site_description: "0xfab1 wiki"
site_author: "Fabian"

theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  language: en
  palette:
    scheme: slate
    primary: green
    accent: yellow
  highlightjs: true
  favicon: icons/favicon.ico
  icon:
    logo: logo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zerogdoubled
    - icon: fontawesome/brands/github
      link: https://github.com/FullByte
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/1132374314/playlists
    - icon: fontawesome/brands/soundcloud
      links: https://soundcloud.com/0gdd
    - icon: fontawesome/brands/docker
      links: https://hub.docker.com/repository/docker/0gdd/0xfab1.net

markdown_extensions:
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      clickable_checkbox: true
