services:
  - type: web
    name: 0xfab1-website
    runtime: static
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m mkdocs build
    staticPublishPath: ./site
    domains:
      - 0xfab1.net
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
      - path: /*
        name: X-Robots-Tag
        value: index, follow
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
