name: mkdocs gh-deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Set up Python 3.9
        with:
          python-version: '3.9'

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install mkdocs-material
          pip install mkdocs-minify-plugin

      - name: Deploy 0xfab1.net
        run: |
          git pull
          mkdocs gh-deploy

      - uses: urlstechie/urlchecker-action@master
      - name: Check URLs
        with:
          subfolder: docs/tech
          file_types: .md
          print_all: false
          timeout: 4
          retry_count: 1
          force_pass : true

      - uses: ShiftLeftSecurity/scan-action@master
      - name: Vuln Scan
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports

      - uses: github/codeql-action/upload-sarif@v1
      - name: Upload report      
        with:
          sarif_file: reports
