# Source: https://github.com/marketplace/actions/urlchecker-action
# Check if URLs from all markdown files within docs folder are valid once a month

name: Check URLs

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: urls-checker
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: docs/tech
        file_types: .md
        print_all: false
        timeout: 4
        retry_count: 1
        force_pass : true
