# Source: https://www.mkdocs.org/user-guide/deploying-your-docs/
# Build mkdocs page on every push using gh-deploy

name: mkdocs gh-deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install mkdocs-material
          pip install mkdocs-minify-plugin

      - name: Deploy 0xfab1.net
        run: |
          git pull
          mkdocs gh-deploy

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check URLs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: docs/tech
        file_types: .md
        print_all: false
        timeout: 4
        retry_count: 1
        force_pass : true

  Scan-Build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1

      - name: Vuln Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports