name: Publish Docker hub Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # Updated to v2 for Node 16 compatibility
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Updated to v2 for Node 16 compatibility
      - name: Checkout
        uses: actions/checkout@v3 # Updated to v3 for Node 16 compatibility
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v2 # Updated to v2 for Node 16 compatibility
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4 # Updated to v4 for Node 16 compatibility
        with:
          context: .
          push: true
          tags: 0xfab1/0xfab1.net:latest
          no-cache: true
